# Site settings

title: artsw0rd dev blog
email: devArtsw0rd7@protonmail.com
description: The Chronic(WHAT?!)cles of my first gig as a developer.
#baseurl: 
#url:
twitter_username: 
github_username:



header_pages:
  - index.md
  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Set blog style
# dark => white text on black background
# light => black text on white background
# hacker => green text on black background
style: hacker # dark (default) light, or hacker

#  Allow users to choose light or dark style based on their preferences 
# (mostly affected by OS dark or light theme 
# For details see https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)
# macOS LIGHT MODE == light style
# macOS DARK MODE == dark style
# USE OF EITHER light or dark will override the hacker style
# listen_for_clients_preferred_style: true # true or false (default)

# Build settings
plugins:
  - jekyll-seo-tag

  